# -*- coding: utf-8 -*-
"""Resposta_Caderno2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RsbJshuAUjQNHCWsgMe6UpNPnypI33hd
"""

# @title Exercicio 2-1
print("Olá mundo!!")

# @title Exercicio 2-2
nome = "Maria"
print(nome)

# @title Exercicio 2-3
num = input("Insira um numero: ")
print(type(num))

# @title Exercicio 2-3 (Variação)
num = float(input("Insira um numero: "))
print(type(num))

# @title Exercicio 2-4
a = 10
b = 5

print(a + b)
print(a - b)
print(a * b)
print(a / b)

# @title Exercicio 2-5
num1 = float(input("Insira o primeiro numero: "))
num2 = float(input("Insira o segundo numero: "))

soma = num1 + num2

print(soma)

# @title Exercicio 2-6
age = int(input("Insira sua idade(sem mentir hein): "))

if age > 18:
  print("Você é um adulto!")
elif age < 18:
  print("Você não é adulto!")

#bonus de codigo

else:
  print("Você acabou de virar adulto")

# @title Exercicio 2-7
numero = int(input("Insira um numero: "))
modular = numero % 2

if modular == 0:
  print("Seu numero é par!!")
else:
  print("Seu numero é impar!!")

# @title Exercicio 2-8
idade = int(input("Insira aqui sua idade(Sem mentir hein): "))

if ((idade >= 18) and (idade <= 65)):
  print("Você é um adulto!!")
else:
  print("Você não é adulto!!")

# @title Exercicio 2-9
idade = int(input("Insira aqui sua idade(Sem mentir hein): "))

if idade > 17:
  print("Você é maior de idade, bora pagar umas contas")
else:
  print("Você é menor de idade... Sortudo")

# @title Exercicios 2-10
nota = int(input("Insira sua nota: "))

if ((nota >= 6) and (nota <= 10)):
  print("Passou! Você é o orgulho da turma!")
elif nota <= 6:
  print("Não passou... Bora estudar mais?")
else:
  print("Numero fora de alcançe")

# @title Exercicio 2-11
num = float(input("Insira um numero: "))

if num > 0:
  print("Positivo... Detesto os produtos dessa marca")
elif num == 0:
  print("Nulo que nem a nota de quem falta")
else:
  print("Negativo que nem minha autoestima ksksk")

# @title Exercicio 2-12
num1 = int(input("Insira o primeiro numero: "))
num2 = int(input("Insira o segundo numero: "))

if num1 > num2:
  print("O primeiro numero é maior")
else:
  print("O segundo numero é maior")

# @title Exercicio 2-13
operacao = str(input("Qual operação deseja realizar?"))
one = float(input("Qual o primeiro numero da operação?"))
two = float(input("Qual o segundo numero da operação?"))

if operacao == "adição":
 print(one + two)
elif operacao == "subtração":
 print(one - two)
elif operacao == "multiplicação":
 print(one * two)
elif operacao == "divisão":
 print(one / two)
else:
 print("Não reconhecido")

# @title Exercicio 2-14
num = int(input("Insira um numero: "))
modular = num % 2

if ((modular == 0)) and ((num > 0)):
  print("Seu numero é par e positivo")
elif ((modular == 1)) and ((num > 0)):
  print("Seu numero é impar e positivo")
elif ((modular == 0)) and ((num < 0)):
  print("Seu numero é par e negativo")
elif num == 0:
  print("Seu numero é par e nulo")
else:
  print("Seu numero é impar e negativo")

# @title Exercicio 2-15
age = int(input("Insira sua idade: "))

if ((age > 0)) and ((age <= 12)):
  print("Você é uma criança")
elif ((age > 12)) and ((age <= 17)):
  print("Você é um adolescente")
elif ((age > 17)) and ((age <= 59)):
  print("Você é um adulto")
elif age > 59:
  print("Você é um idoso")
else:
  print("Você não tem um valor de idade comum")

# @title Exercicio 2-16
calculo = (2 + 3) * 4 - 5 / 2 * (2 + 3) * 4 - 5 / 2

print(calculo)

# @title Exercicio 2-17
base = 2
potencia = base ** 2

print(potencia)

# @title Exercicio 2-18
import math

r = 5 ** 2
pi = 3.14
Area = pi * r

print(Area)